from colorama import Fore, Style, init
init(autoreset=True)

EngToUrdu = {
"believer":"momin",
"disbeliever":"kafir",
"prophet":"nabi / rasool",
"paradise":"jannat",
"hell":"jahannam",
"angel":"farishta",
"merciful":"rahmaan",
"compassionate":"raheem",
"prayer":"namaz",
"fasting":"roza",
"charity":"zakat",
"pilgrimage":"hajj",
"faith":"iman",
"islam":"islam",
"quran":"qur'an",
"hadith":"hadees",
"mosque":"masjid",
"supplication":"dua",
"repentance":"tauba",
"patience":"sabr",
"gratitude":"shukr",
"truth":"haq",
"falsehood":"batil",
"halal":"halal",
"forbidden":"haram",
"day of judgment":"qayamat",
"resurrection":"hashr",
"heavenly book":"asmani kitab",
"destiny":"taqdeer",
"knowledge":"ilm",
"scholar":"aalim",
"worship":"ibadat",
"creator":"khaliq",
"sustainer":"raziq",
"forgiver":"ghafoor",
"peace":"salaam",
"brotherhood":"bhaichara",
"community":"ummah",
"leader":"imam",
"sermon":"khutbah",
"friday prayer":"jummah",
"call to prayer":"azaan",
"ablution":"wuzu",
"purity":"taharat",
"heart":"dil",
"soul":"rooh",
"world":"duniya",
"hereafter":"aakhirat",
"light":"noor",
"guidance":"hidayat",
"straight path":"sirat-e-mustaqeem",
"good deed":"neki",
"sin":"gunah",
"reward":"sawaab",
"punishment":"azaab",
"grave":"qabr",
"funeral":"janazah",
"martyr":"shaheed",
"struggle":"jihad",
"reminder":"naseehat",
"justice":"adl",
"kindness":"rehmat",
"trust":"amanat",
"promise":"wada",
"intention":"niyyat",
"effort":"koshish",
"success":"kamiyabi",
"test":"aazmaish",
"trial":"imtihan",
"blessing":"barkat",
"provision":"rizq",
"protection":"hifazat",
"enemy":"dushman",
"friend":"dost",
"family":"khandan",
"marriage":"nikah",
"wife":"biwi",
"husband":"shauhar",
"children":"aulad",
"parents":"walidain",
"mother":"ammi",
"father":"abbu",
"respect":"ehtram",
"love":"mohabbat",
"hope":"umeed",
"fear":"khauf",
"reliance":"tawakkul",
"remembrance":"zikr",
"glorification":"tasbeeh",
"praise":"hamd",
"thanks":"shukriya",
"greatness":"azmat",
"power":"qudrat"
}

while True:
    dicWord = input("Enter Word (type exit program stop): ").lower().strip()
    if dicWord == "exit":
       print("program ended")
       break

    elif dicWord == "":
        print("Enter word...")
    
    elif dicWord in EngToUrdu:
        print(EngToUrdu[dicWord])
    else:
        print("Word not found")